# Generated by Django 3.2.5 on 2021-11-17 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20211116_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_of_joining',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='from@example.com', max_length=254, unique=True),
        ),
    ]
