# Generated by Django 3.2.5 on 2021-12-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolio_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='bio',
        ),
    ]
